buyacar/core/views.py
from flask import render_template, request, Blueprint, session, redirect, url_for, jsonify
from buyacar.models import db, Car, Client

from buyacar.core.forms import PurchaseForm
import json
import stripe

# This is your test secret API key.
stripe.api_key = 'sk_test_51Oyfo6P7tQOhIrsaoqV41g2YaSDc2cAB6Qjt4tXoKWfVkQ6eAhRqatbYrHxKhi71AbiAOgV4y3HL0TfL3Myjl82I003C2UEtc4'

# Creates blueprint for core
core = Blueprint('core', __name__)

# Function to load data from CSV, to be called only once
#@app.before_first_request

@core.route('/')
def index():    
    return render_template('index.html')

# Route for displaying all cars without any filters
@core.route('/cars')
def cars():
    page = request.args.get('page', 1, type=int)
    filters = {}
    priceFilters = {}
    # Loads distinct values for all filters
    makes = Car.query.with_entities(Car.make).distinct().all()
    models = Car.query.with_entities(Car.model).distinct().all()
    towns = Car.query.with_entities(Car.town).distinct().all()
    regions = Car.query.with_entities(Car.region).distinct().all()
    # Query to get all cars
    query = Car.query
    cars = query.paginate(page=page, per_page=6)
    return render_template('cars.html', cars=cars, filters=filters, priceFilters=priceFilters, makes=makes, models=models, towns=towns, regions=regions)

@core.route('/filtered-cars', methods=['GET', 'POST'])
def filtered_cars():
    page = request.args.get('page', 1, type=int)

    # Defines filters dictionary
    if request.method == 'POST':
        # Updates session with form data for each filter
        session['make'] = request.form.get('make')
        session['model'] = request.form.get('model')
        session['town'] = request.form.get('town')
        session['region'] = request.form.get('region')
        session['minPrice'] = request.form.get('minPrice')
        session['maxPrice'] = request.form.get('maxPrice')

    # Checks for GET request and updates session (for images in index.html)
    if request.method == 'GET':
        session['make'] = request.args.get('make')
        session['model'] = request.args.get('model')

        
    # Loads distinct values for all filters
    makes = Car.query.with_entities(Car.make).distinct().all()
    models = Car.query.with_entities(Car.model).distinct().all()
    towns = Car.query.with_entities(Car.town).distinct().all()
    regions = Car.query.with_entities(Car.region).distinct().all()

    # Retrieves session data to maintain filter state and stores in a dictionary
    filters = {
        'make': session.get('make'),
        'model': session.get('model'),
        'town': session.get('town'),
        'region': session.get('region')
    }
    # Retrieves min and max price from session and stores into a separate dictionary
    priceFilters = {
        'minPrice': session.get('minPrice'),
        'maxPrice': session.get('maxPrice')
    }
    # Builds query based on session filters
    query = Car.query
    for key, value in filters.items():
        if value:
            query = query.filter(getattr(Car, key) == value)    

    # Filters by price range if both min and max prices are provided    
    if priceFilters['minPrice'] and priceFilters['maxPrice']:
        query = query.filter(Car.price.between(priceFilters['minPrice'], priceFilters['maxPrice']))
    elif priceFilters['minPrice']:
        query = query.filter(Car.price >= priceFilters['minPrice'])
    elif priceFilters['maxPrice']:
        query = query.filter(Car.price <= priceFilters['maxPrice'])    

    # Execute the query and paginate results
    cars = query.paginate(page=page, per_page=6)
    return render_template('cars.html', cars=cars, filters=filters, priceFilters=priceFilters, makes=makes, models=models, towns=towns, regions=regions)
 
@core.route('/clear-filters')
def clear_filters():
    # List of filter keys to clear from the session
    filter_keys = ['make', 'model', 'town', 'region', 'colour', 'miles', 'price_min', 'price_max']
    # Clear each filter key from the session
    for key in filter_keys:
        session.pop(key, None)
    # Redirects back to the cars page
    return redirect(url_for('core.cars'))

# Handles AJAX request and returns models for a selected make
@core.route('/get-models/<make>')
def get_models(make):
    models = Car.query.filter_by(make=make).with_entities(Car.model).distinct().all()
    model_list = [model[0] for model in models]  # Converts to a simple list
    return jsonify(model_list)

# Handles AJAX request and returns towns for a selected model
@core.route('/get-towns/<model>')
def get_towns(model):
    towns = Car.query.filter_by(model=model).with_entities(Car.town).distinct().all()
    town_list = [town[0] for town in towns]  # Converts to a simple list
    return jsonify(town_list)

# Handles AJAX request and returns regions for a selected model
@core.route('/get-regions/<model>')
def get_regions(model):
    regions = Car.query.filter_by(model=model).with_entities(Car.region).distinct().all()
    region_list = [region[0] for region in regions]  # Converts to a simple list
    return jsonify(region_list)

@core.route('/carform/<int:car_id>', methods=['GET','POST'])
def carform(car_id):
    car = Car.query.filter_by(carIndex=car_id).first()
    form = PurchaseForm()
    if form.validate_on_submit():
        client = Client(name=form.name.data,
                        surname=form.surname.data,
                        email=form.email.data,
                        phone=form.telephone.data,
                        address=form.address.data,
                        town=form.town.data,
                        postcode=form.postcode.data                        
                    )        
        db.session.add(client)
        db.session.commit() 
        car.client_id = client.id
        db.session.add(car)
        db.session.commit()      
        return redirect(url_for('core.checkout', car_id=car.carIndex))    
    return render_template('carform.html', car=car, form=form)

@core.route('/checkout/<int:car_id>')
def checkout(car_id):
    car = Car.query.get(car_id) 
       
    return render_template('checkout.html', car=car)

@core.route('/create-payment-intent/<car_price>', methods=['GET', 'POST'])
def create_payment(car_price):
    # Convert car_price to an integer
    try:
        data = json.loads(request.data)
        # Create a PaymentIntent with the order amount and currency
        intent = stripe.PaymentIntent.create(
            amount=car_price,
            currency='gbp',
            # In the latest version of the API, specifying the `automatic_payment_methods` parameter is optional because Stripe enables its functionality by default.
            automatic_payment_methods={
                'enabled': True,
            },
        )
        return jsonify({
            'clientSecret': intent['client_secret']
        })
    except Exception as e:
        return jsonify(error=str(e)), 403

@core.route('/thankyou/<car_id>')
def thankyou(car_id):
    car = Car.query.get(car_id) 
    
    return render_template('thankyou.html', car=car)
    

buyacar/user/views.py
from flask import render_template, request, Blueprint, session, redirect, url_for, flash
from buyacar.models import db, Car, Client, User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user


# Creates blueprint for admin
users = Blueprint('users', __name__)

@users.route("/login", methods=['GET','POST'])
def login():
    # Creates new admin user with name admin and hashed password admin123
    #password = 'admin123'
    #name = 'admin1'
    #newuser = User(name=name, password=generate_password_hash(password, method='pbkdf2'))
    # Adds the new user to the database
    #db.session.add(newuser)
    #db.session.commit()
    # Gathers entered name and password 
    name = request.form.get('name')
    password = request.form.get('password')
    # Filters User database to find the user name
    user = User.query.filter_by(name=name).first()
    # Checks if user with that name or password was found
    if not user or not check_password_hash(user.password, password):  
        if request.method == 'POST':      
            flash('Please check your login details and try again.')
        return render_template('login.html') # if the user doesn't exist or password is wrong, reloads the page
    # Grabs logged user id
    login_user(user)
    return redirect(url_for('admin.index'))

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

buyacar/templates/base.html
<!DOCTYPE html>
<html lan="en" dir="ltr">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/style.css">        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/466749fc41.js" crossorigin="anonymous"></script>
        <script src="https://js.stripe.com/v3/"></script>         
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg", id="topNavigation">
            <div class="container-fluid justify-content-center", id="navigation">
                <a class="navbar-brand mx-4" href="{{ url_for('core.index') }}">
                    <img src="{{ url_for('static', filename='Logo.png') }}" alt="logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav text-center" id="navbar">
                        <li class="nav-item nav-fill">
                            <a class="nav-link" aria-current="page" href="{{ url_for('core.index') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.cars') }}">Buy</a>
                        </li>
                        {% if not current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                        {% endif %}                        
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid" style="width: 80%">
        {% block content %}
        {% endblock %}
        </div>
        
        <!-- Footer -->
        <footer class="text-center text-lg-start text-muted">
            <!-- Section: Social media -->
            <section class="pe-4 pt-4 d-flex justify-content-center", id="socialMedia">
                <!-- Left -->
                <div class="mt-2 me-3 d-none d-sm-block">
                    <span>Connect with us on social networks: </span>
                </div>
                
                <!-- Left -->

                <!-- Right -->
                <div>
                    <!-- Facebook -->
                    <a
                        data-mdb-ripple-init
                        class="btn text-white btn-floating m-1"
                        style="background-color: #3b5998;"
                        href="#!"
                        role="button"
                        ><i class="fab fa-facebook-f"></i
                    ></a>
                    <!-- X -->
                    <a
                        data-mdb-ripple-init
                        class="btn text-white btn-floating m-1"
                        style="background-color: #333333;"
                        href="#!"
                        role="button"
                        ><i class="fa-brands fa-x-twitter"></i
                    ></a>
                    <!-- Instagram -->
                    <a
                        data-mdb-ripple-init
                        class="btn text-white btn-floating m-1"
                        style="background-color: #ac2bac;"
                        href="#!"
                        role="button"
                        ><i class="fab fa-instagram"></i
                    ></a>

                    <!-- Linkedin -->
                    <a
                        data-mdb-ripple-init
                        class="btn text-white btn-floating m-1"
                        style="background-color: #0082ca;"
                        href="#!"
                        role="button"
                        ><i class="fab fa-linkedin-in"></i
                    ></a>
                </div>
                <!-- Right -->
            </section>
            <!-- Section: Social media -->

            <!-- Section: Links  -->
            <section class="mainFooter">
                <div class="container text-center text-md-start ">
                <!-- Grid row -->
                    <div class="row">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-4 col-xl-3 mt-2 mx-auto mb-4">
                        <!-- Content -->
                            <a href="{{ url_for('core.index') }}">
                                <img src="{{ url_for('static', filename='Logo.png')}}" alt="logo">
                            </a>
                            <p>
                                Search, find and buy your next quality checked car online.
                            </p>
                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mt-4 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                                Site Links
                            </h6>
                            <p>
                                <a href="{{ url_for('core.index') }}" class="text-reset">Home</a>
                            </p>
                            <p>
                                <a href="{{ url_for('core.cars') }}" class="text-reset">Buy</a>
                            </p>
                            <p>
                                <a href="{{ url_for('users.login') }}" class="text-reset">Login</a>
                            </p>
                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-2 col-xl-2 mt-4 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                                Useful links
                            </h6>
                            <p>
                                <a href="https://www.gocompare.com/" target="_blank" class="text-reset">Insurance</a>
                            </p>
                            <p>
                                <a href="https://www.carfinance247.co.uk/" target="_blank" class="text-reset">Finances</a>
                            </p>
                            <p>
                                <a href="https://www.webuyanycar.com/" target="_blank" class="text-reset">Car sales</a>
                            </p>
                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-md-4 col-lg-3 col-xl-3 mt-4 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                            <p><i class="fas fa-home me-3"></i> 52 Cowgate, Peterborough, PE1 1NA</p>
                            <p>
                                <i class="fas fa-envelope me-3"></i> info@buyacar.co.uk</p>
                            <p><i class="fas fa-phone me-3"></i> 01733 345634</p>
                        </div>
                        <!-- Grid column -->
                    </div>
                    <!-- Grid row -->
                </div>
            </section>
            <!-- Section: Links  -->

        <!-- Copyright -->
            <div class="text-center p-4" style="background-color: #AC94D4; color: #080808;">
                © 2024 Copyright: BuyaCar Ltd.
            </div>
        <!-- Copyright -->
        </footer>
        <!-- Footer -->
        <script src="{{ url_for('static', filename='global.js') }}"></script>
    </body>
</html>

buyacar/templates/carform.html
{% extends "base.html" %}
{% block title %}
    {{ car.make }} {{ car.model }}
{% endblock %}
{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb mt-4">
      <li class="breadcrumb-item"><a href="{{ url_for('core.index') }}">Home</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('core.cars') }}">Cars</a></li>
      <li class="breadcrumb-item active" aria-current="page">Car form</li>
    </ol>
</nav>
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-9 mt-4 mb-4">            
            <div class="form-horizontal">                    
                <h2 class="text-center">About you</h2>
                <form method="POST">
                    {# This hidden_tag below is a CSRF security feature #}
                    {{ form.hidden_tag() }}
                    <div class="row mt-3 mb-3">
                        {{ form.name.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.name(class="form-control form-control", placeholder="First name") }}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.surname.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.surname(class="col-10 form-control form-control", placeholder="Last name") }}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.email.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.email(class="col-10 form-control form-control", placeholder="Email")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.telephone.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.telephone(class="col-10 form-control form-control", placeholder="Phone number")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.address.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.address(class="col-10 form-control form-control", placeholder="Address")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.town.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.town(class="col-10 form-control form-control", placeholder="Town")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.postcode.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.postcode(class="col-10 form-control form-control", placeholder="Postcode")}}
                        </div>
                    </div>                            
                    <div class="form-group">
                        <button type="button" class="btn btn-secondary float-end" data-bs-toggle="modal" data-bs-target="#myModal">
                            Continue
                        </button>
                    </div>
                    <!-- The Modal -->
                    <div class="modal" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">  
                                <!-- Modal Header -->
                                <div class="modal-header">                        
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>  
                                <!-- Modal body -->
                                <div class="modal-body">
                                    <h5>Please, confirm that the data you provided in the form is correct.</h5>
                                </div>  
                                <!-- Modal footer -->
                                <div class="modal-footer">                                    
                                    {{ form.submit(class="btn btn-success")}}
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                                     
                                </div>  
                            </div>
                        </div>
                    </div>
                </form>                    
            </div>            
        </div>        
        <div class="col-lg-3 mt-4 mb-4 text-center">
            <div class="card bg-light"> 
                <img class="card-img-top rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}">       
                <div class="card-body">        
                    <h4 class="card-title">{{ car.make }} {{ car.model }}</h4>
                    <p class="card-text">Car identification number: {{ car.carIndex }}</p>                       
                    <p class="card-text"><i class="fa-solid fa-city"></i> {{ car.town }}</p>
                    <p class="card-text">Dealer information: {{ car.dealer }} </p>
                    <p class="card-text">{{ car.telephone }}</p>
                    <h3 class="card-title">£{{ car.price }}</h3>      
                </div>
            </div>  
        </div>
    </div>
</div> 
{% endblock %}

buyacar/templates/cars.html
{% extends "base.html" %}
{% block title %}
    Cars
{% endblock %}
{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb mt-4">
      <li class="breadcrumb-item"><a href="{{ url_for('core.index') }}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Cars</li>
    </ol>
</nav>
<div class="container-fluid mt-4">
  <div class="row">
    <div class="col-lg-4 mt-4 mb-4">
      <!-- Displays active filters -->
        <div class="filters mb-4">
          <h2>Filters</h2>
          {% if filters.make %}<span>Make: {{ filters.make }}</span>{% endif %}
          {% if filters.model %}<span>Model: {{ filters.model }}</span>{% endif %}
          {% if filters.town %}<span>Town: {{ filters.town }}</span>{% endif %}
          {% if filters.region %}<span>Region: {{ filters.region }}</span>{% endif %}
          {% if priceFilters.minPrice %}<span>Min price: {{ priceFilters.minPrice }}</span>{% endif %}
          {% if priceFilters.maxPrice %}<span>Max price: {{ priceFilters.maxPrice }}</span>{% endif %}
              <!-- Clear Filters Button -->
          <form method="get" action="{{ url_for('core.clear_filters') }}">
            <button type="submit" class="btn btn-secondary btn-md" id="clearFilter" aria-label="Clear the filters">Clear all filters</button>
          </form>
        </div>
        <form method="post" action="{{ url_for('core.filtered_cars') }}">
          <div>
            <select name="make" class="form-select form-select-lg mb-3", id="makeDropdown" aria-label="Select make for a car">
              <option value="">Select Make</option>
              {% for make in makes %}
              <option value="{{ make[0] }}">{{ make[0] }}</option>
              {% endfor %}
            </select>
          </div>
          <div>
            <select name="model" class="form-select form-select-lg mb-3", id="modelDropdown" aria-label="Select model for a car">
              <option value="">Select Model</option>
              {% for model in models %}
              <option value="{{ model[0] }}">{{ model[0] }}</option>
              {% endfor %}
              </select>
          </div>
          <div>
            <select name="town" class="form-select form-select-lg mb-3", id="townDropdown" aria-label="Select town for a car">
              <option value="">Select Town</option>
              {% for town in towns %}
              <option value="{{ town[0] }}">{{ town[0] }}</option>
              {% endfor %}
            </select>
          </div>
          <div>
            <select name="region" class="form-select form-select-lg mb-3", id="regionDropdown" aria-label="Select region for a car">
              <option value="">Select Region</option>
              {% for region in regions %}
              <option value="{{ region[0] }}">{{ region[0] }}</option>
              {% endfor %}
            </select>
          </div>          
          <div class="input-group mb-4">
            <span class="input-group-text">Min £</span>
            <input type="text" name="minPrice" class="form-control form-control-lg" aria-label="Insert min amount" placeholder="min amount">
          </div>          
          <div class="input-group mb-4">
            <span class="input-group-text">Max £</span>
            <input type="text" name="maxPrice" class="form-control form-control-lg" aria-label="Insert max amount" placeholder="max amount">
          </div>          
          <button type="submit" class="btn btn-secondary btn-md" id="applyFilter" aria-label="Apply filters">Apply selected filters</button>
        </form>
    </div>
  
    <div class="col-lg-8 mt-4 mb-4 text-center">
      <h2>Results</h2>
      <!-- Display cars -->
      {% for car in cars.items %}
      <div class="card flex-row bg-light">        
        <div class="card-body">
          <div class="block"><img class="float-start img-fluid object-fit-scale border rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}"></div>
          <h4 class="card-title">{{ car.make }}</h4>
          <h5 class="card-subtitle mb-2 text-body-secondary">{{ car.model }}</h5>
          <h6><i class="fa-solid fa-palette"></i> {{ car.colour }} <i class="fa-solid fa-gauge-high"></i> {{ car.miles }}</h6>
          <h5><i class="fa-solid fa-city"></i> {{ car.town }}</h5>
          <p class="card-text">{{ car.description }}</p>
          <h3 class="card-title">£{{ car.price }}</h3>
          <button type="button" class="btn btn-secondary" id="carButton" aria-label="Open modal to view more details" data-bs-toggle="modal" data-bs-target="#modal{{ car.carIndex }}">View deal</button>
        </div>
      </div>      
        <!-- The Modal -->
        <div class="modal fade" id="modal{{ car.carIndex }}">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
            <!-- Modal Header -->
              <div class="modal-header">
                <h5 class="float-start text-muted me-4">{{ car.carIndex }}</h5>
                <h4 class="modal-title">{{ car.make }} {{ car.model }}</h4>
                <button type="button" class="btn-close" aria-label="Close modal" data-bs-dismiss="modal"></button>
              </div>
            <!-- Modal body -->
              <div class="modal-body">
                <div class="block"><img class="float-start img-fluid object-fit-scale border rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}"></div>
                <div class="mt-4 mb-4">
                  <h5><i class="fa-solid fa-registered"></i> {{car.reg }} <i class="fa-solid fa-gauge-high"></i> {{ car.miles }}</h5> 
                  <h5><i class="fa-solid fa-palette"></i> {{ car.colour }}</h5>
                  <h6><i class="fa-solid fa-circle-info"></i> {{car.description }}</h6>
                  <h6>Region: {{ car.region }}</h6> 
                  <h6> <i class="fa-solid fa-city"></i> {{ car.town }}</h6> 
                  <h6><i class="fa-solid fa-briefcase"></i> {{ car.dealer }}</h6>
                  <h6><i class="fa-solid fa-phone"></i> {{ car.telephone }}</h6>
                </div>
              </div>
              <!-- Modal footer -->
              <div class="modal-footer">
                <h3>£{{ car.price }}</h3>
                <a href="{{ url_for('core.carform', car_id=car.carIndex ) }}" aria-label="Buy this car" class="btn btn-success">Buy</a>
                <button type="button" class="btn btn-danger" aria-label="Close modal" data-bs-dismiss="modal">Close</button>
              </div>              
            </div>
          </div>
        </div> 
        {% endfor %}     
      <nav class="mt-4" aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          <!-- Description of dynamic route if there are session data then @core.filtered-cars if no session data then @core.cars -->
          {% set route_name = 'core.filtered_cars' if session.get('make') or session.get('model') or session.get('town') or session.get('region') or session.get('minPrice') or session.get('maxPrice') else 'core.cars' %}
          {% if cars.has_prev %}
            <li class="page-item">
              <!-- Dynamic routing in url_for function to access @core.cars or @core.filtered-cars according to session data -->
              <a class="page-link" href="{{ url_for(route_name, page=cars.prev_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for page_num in cars.iter_pages() %}
            <li class="page-item {% if page_num == cars.page %}active{% endif %}">
              <a class="page-link" href="{{ url_for(route_name, page=page_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">{{ page_num }}</a>
            </li>
          {% endfor %}
          {% if cars.has_next %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for(route_name, page=cars.next_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>      
    </div>
  </div>
</div>
{% endblock %}